config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth'
             }

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/users/auth/callback', to: 'omniauth#github'

  resources :users do
    member do
      get :friends
    end
  end

  resources :posts
  resources :comments

  resources :likes
  resources :friendships
  get :pending_requests, to: 'friendships#pending'

  # get '*path' => redirect('users')
  # match '*path', to: 'application#routing_error', via: %i[get post]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    # debugger
    if @comment.save
      flash[:success] = 'Comment created successfully!'
    else
      flash[:warning] = 'There was a error while creating comment!'
    end
    redirect_to request.referer || root_url

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    return unless @comment

    @comment.destroy
    flash[:success] = 'Comment was deleted successfully'
    redirect_to request.referer || root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end

  # def fin
  #   @post = current_user.posts.find_by(id: params[:id])
  #   redirect_to root_url if @post.nil?
  # end
end

app/views/comments/_comment.html.erb
<div class="comment-container">
  <div class="comment">
    <%# debugger %>
    <span class="comment-user"><%= link_to comment.user.name, user_path(comment.user)%> </span>
    <span class="comment-content">- <%= comment.content %></span>
  </div>
  <% if comment.user.id == current_user.id %>
    <%= link_to(comment_path(comment.id), method: :delete, class: "comment-delete") do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
  <% end %>
</div>
<%= render partial: 'likes/button', locals: { likeable: comment } %>

app/views/comments/_new_comment.html.erb
<%= form_with(model: Comment.new,local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_area :content, placeholder: "Write a comment...", class: "new-comment" %>
  <%= f.hidden_field :post_id, value: post.id %>
  <div class="button">
    <%= f.button name: "comment-button" do %>
      <i class="fa-solid fa-comment"></i>
    <% end %>
  </div>
<% end %>