config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth'
             }

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/users/auth/callback', to: 'omniauth#github'

  resources :users do
    member do
      get :friends
    end
  end

  resources :posts
  resources :comments

  resources :likes
  resources :friendships
  get :pending_requests, to: 'friendships#pending'

  # get '*path' => redirect('users')
  # match '*path', to: 'application#routing_error', via: %i[get post]
end

app/views/shared/_error_messages.html.erb
<% if object&.errors&.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains
      <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%# doubt %>
    <%#= @feed_items.each do |post| %>
      <%#= render post %>
    <%# end %>
  <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "What's in your mind?" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>

  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
    $("#post_image").bind("change", function() {
        const size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#post_image").val("");
        }
    });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= friends_user_path(@user) %>">
    <strong class="stat">
      <%= @user.friends.count %>
    <%='Friend'.pluralize(@user.friends.count) %>
    </strong>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 150), current_user %>
<h1><%= current_user.name %></h1>

<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>