config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth'
             }

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/users/auth/callback', to: 'omniauth#github'

  resources :users do
    member do
      get :friends
    end
  end

  resources :posts
  resources :comments

  resources :likes
  resources :friendships
  get :pending_requests, to: 'friendships#pending'

  # get '*path' => redirect('users')
  # match '*path', to: 'application#routing_error', via: %i[get post]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: 'must be a valid image format' },
                      size: { less_than: 5.megabytes,
                              message: 'should be less than 5MB' }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :find_user, only: %i[edit update destroy]

  def index
    # debugger
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])

    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to root_url
    else
      @feed_items = current_user.feed
      render 'static_pages/home'
    end
  end

  def edit
    @title = 'Edit Page'
  end

  def update
    # debugger
    if @post.update(post_params)
      flash[:success] = 'Post updated successfully'
      redirect_to root_url
    else
      flash[:warning] = 'Something went wrong, post not edited'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted successfully'
    if request.referrer.nil? || request.referrer == posts_url
      redirect_to root_url
    else
      redirect_to request.referrer
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def find_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
#fsgshgcdshjchjdscbdsjcdskjcndscsdjk
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="posts">
  <header>
    <div class="name-container">
      <%# debugger %>
      <%= link_to gravatar_for(post.user, size: 50), post.user %>
      <h3 class="post-user-name"><%=link_to post.user.name, user_path(post.user)%></h3>
      <time class="post-time" datetime="<%=post.created_at%>"> <%= time_ago_in_words(post.created_at) %>
        ago.
      </time>
    </div>
    <% if current_user?(post.user) %>
      <div class="dropdown">
        <button class="dropbtn">
          <i class="fas fa-ellipsis-v"></i>
        </button>
        <div class="dropdown-content">
          <%= link_to 'Edit', edit_post_path(post.id) %>
          <%= link_to 'Delete', post_path(post.id), method: :delete %>
        </div>
      </div>
    <% end %>
  </header>
  <p class="post-content"><%= post.content %></p>
  <%= image_tag post.display_image if post.image.attached? %>
  <%# debugger %>
  <%= render partial: 'likes/button', locals: { likeable: post } %>
  <%#debugger %>
  <% if post.comments.any? %>
    <%#= render partial: 'comments/comment', locals: {comment: post.comments} %>
    <%= render post.comments %>
<% end %>
  <%= render 'comments/new_comment', post: post %>
</div>

app/views/posts/edit.html.erb
<% provide(:title, @title) %>

<div class="container">
  <h3>Update your post</h3>
  <div>
    <%= form_with( model: @post, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_area :content%>
      <%= f.submit "Update post", class: "btn btn-primary" %>

      <span>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </span>
    <% end %>
  </div>
</div>