config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               omniauth_callbacks: 'omniauth'
             }

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/users/auth/callback', to: 'omniauth#github'

  resources :users do
    member do
      get :friends
    end
  end

  resources :posts
  resources :comments

  resources :likes
  resources :friendships
  get :pending_requests, to: 'friendships#pending'

  # get '*path' => redirect('users')
  # match '*path', to: 'application#routing_error', via: %i[get post]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top fb-color">
  <div class="container">
    <%= link_to "facebook", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <% if user_signed_in? %>
          <% pending_friends = current_user.pending_friends_list %>

          <li><%= link_to "Home", root_path %></li>
          <li>
            <%= link_to users_path do %>
              <i class="fa-solid fa-users"></i>
            <% end %>
          </li>

          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa-solid fa-bell"></i> <b class="caret"></b>
                <% if pending_friends.any? %>
                  <span class="badge"><%= pending_friends.count %></span>
                  <%= render 'layouts/pending_friends_list_page' %>
                <% end %>
              </a>
          </li>

          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

        <%else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <%end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_pending_friends_list_page.html.erb
<% pending_friends = current_user.pending_friends_list %>

<ul class="dropdown-menu">
  <% pending_friends.each do |user| %>
    <li><%= link_to user.name, user %></li>
  <% end %>
  <li class="divider"></li>
  <li><%= link_to 'See all', pending_requests_path, class: 'dropdown-item' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Facebook-Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
  </body>
</html>